### PR TITLE
pkp/pkp-lib#8340 Add pricing to purchase form (bootstrap port)

### PR DESCRIPTION
**Pull request by asmecher**
@NateWr, here is a port of pkp/pkp-lib#8340 to Bootstrap3, which contains a copy of the same template code as the default theme. This is suitable for both `master` and `stable-3_3_0` (but I've only opened the PR for `master`). (When you get a sec, I'd recommend renaming the branch to `main` as well -- or if you like, moving ownership over to PKP so we can distribute the management of the repo).

### CODE REVIEW

**Comment by NateWr** [comment]
In the past, we have tried to be clear that this is a "community" theme and not one of PKP's official themes that we maintain. But I definitely haven't kept this theme up very well. If you want PKP to maintain it, I'm happy to transfer it over.

**Comment by asmecher** [comment]
I think the lesser evil is probably to hold all the themes we maintain under PKP, and try to update them as a set when we work on any one (e.g. porting changes like this across consistenly). So yes, on balance I'd suggest we move this over to PKP. But we can distinguish between formally maitained and less formally maintained using its status in the plugin gallery...

**Comment by NateWr** [comment]
Ok, it's now at pkp/bootstrap3

**Comment by asmecher** [comment]
Thanks, @NateWr! I've...
- Merged this PR
- Cherry-picked it to `stable-3_3_0`
- Renamed the `master` branch to `main` for consistency with our other repos.

**Pull request merged**
